FROM golang:1.8
MAINTAINER jaehue@jang.io

# install go package
RUN go get golang.org/x/sys/... && \
    go get golang.org/x/text/... && \
    go get golang.org/x/net/... && \
    go get golang.org/x/crypto/...
