FROM pangpanglabs/java8

MAINTAINER pangpanglab <pangpanglab@p2shop.cn> 

RUN mkdir -p /opt/pangpang \
	&& mkdir -p /opt/pangpang/bin \
	&& curl -SL http://mirrors.cnnic.cn/apache/nifi/1.1.2/nifi-1.1.2-bin.tar.gz \ 
  	| tar -xzC /opt/pangpang 
